export { default as Quadrado } from './Quadrado.js'
export { default as Triangulo } from './Triangulo.js'
export { default as Cubo } from './Cubo.js'
export { default as CuboTextura } from './CuboTextura.js'
export { default as Piramide } from './Piramide.js'
